var _____WB$wombat$assign$function_____ = function(name) {return (self._wb_wombat && self._wb_wombat.local_init && self._wb_wombat.local_init(name)) || self[name]; };
if (!self.__WB_pmw) { self.__WB_pmw = function(obj) { this.__WB_source = obj; return this; } }
{
  let window = _____WB$wombat$assign$function_____("window");
  let self = _____WB$wombat$assign$function_____("self");
  let document = _____WB$wombat$assign$function_____("document");
  let location = _____WB$wombat$assign$function_____("location");
  let top = _____WB$wombat$assign$function_____("top");
  let parent = _____WB$wombat$assign$function_____("parent");
  let frames = _____WB$wombat$assign$function_____("frames");
  let opener = _____WB$wombat$assign$function_____("opener");


if(typeof window.Csp=='undefined'){window.Csp={};}
Csp.SearchComponent=function(withSiteScoping,withAutoScoping,searchWebHidden,withWatermark,watermarkText,searchBoxContainerId,searchTextBoxId,searchSiteButtonId,searchWebButtonId,scopingDropdownLinkId,scopingMenuContainerId){this.WithSiteScoping=withSiteScoping;this.WithAutoScoping=withAutoScoping;this.SearchWebHidden=searchWebHidden;this.WithWatermark=withWatermark;this.WatermarkText=watermarkText;this.SearchBoxContainerId=searchBoxContainerId;this.SearchTextBoxId=searchTextBoxId;this.SearchSiteButtonId=searchSiteButtonId;this.SearchWebButtonId=searchWebButtonId;this.DropdownLinkId=scopingDropdownLinkId;this.ScopingMenuContainerId=scopingMenuContainerId;this.isOpen=false;this.init();};Csp.SearchComponent.prototype={init:function(){var _this=this;$('#'+this.SearchSiteButtonId).click(function(){_this.search_onClick('mscom');});$('#'+this.SearchWebButtonId).click(function(){_this.search_onClick('live');});if(this.WithWatermark==true){$('#'+this.SearchTextBoxId).blur(function(){_this.setWatermark(false);}).focus(function(){_this.clearWatermark();});this.setWatermark(true);}
if(this.WithSiteScoping==true&&this.WithAutoScoping==false){var ddLink=$('#'+this.DropdownLinkId);if(ddLink.length){ddLink.toggle(Function.createDelegate(this,this.openMenu_onClick),Function.createDelegate(this,this.closeMenu_onClick));$('#'+this.SearchPanelId+' span.src_box, #'+this.ScopingMenuContainerId).mouseover(Function.createDelegate(this,this.clearMenuTimer));$("body").mouseover(Function.createDelegate(this,this.startMenuTimer));}}},setWatermark:function(always){var el=$('#'+this.SearchTextBoxId);if(always==true&&el.val().length>0&&el.val()!=this.WatermarkText){this.clearWatermark();}else if(always==true||el.val().length==0){el.addClass('src_watermark').val(this.WatermarkText);}},clearWatermark:function(){var el=$('#'+this.SearchTextBoxId);if(el.val()==this.WatermarkText){el.removeClass('src_watermark').val('');}else{el.removeClass('src_watermark');}},search_onClick:function(stype){var el=$('#'+this.SearchTextBoxId);var sterm;if(el.val()!=this.WatermarkText){sterm=el.val();}
if(typeof window.DCSext!='undefined'){DCSext.sterm=sterm||'*';DCSext.stype=stype;}},openMenu:function(){var h=$('#'+this.SearchPanelId+' span.src_box').height()-1;if($('body').hasClass('rtl')==true){$('#'+this.ScopingMenuContainerId).css({'display':'inline-block','top':h+'px','left':'-1px'});}else{$('#'+this.ScopingMenuContainerId).css({'display':'inline-block','top':h+'px','right':'-1px'});}
this.isOpen=true;},closeMenu:function(){$('#'+this.ScopingMenuContainerId).css('display','none');this.isOpen=false;},startMenuTimer:function(e){var fnHide=function(){this.hideTimer=undefined;if(this.isOpen==true){$('#'+this.DropdownLinkId).click();}};if(!this.hideTimer){this.hideTimer=window.setTimeout(Function.createDelegate(this,fnHide),300);}},clearMenuTimer:function(e){e.stopPropagation();if(this.hideTimer){window.clearTimeout(this.hideTimer);this.hideTimer=undefined;}},openMenu_onClick:function(e){e.preventDefault();this.openMenu();},closeMenu_onClick:function(e){e.preventDefault();this.closeMenu();}};

if(typeof window.Csp=="undefined"){window.Csp={};}
Csp.Menu=function(id){this._id=id;this._menu=document.getElementById(id);this._hider=null;this._shower=null;$().keypress(Function.createDelegate(this,this.bodyKeyPress)).mouseover(Function.createDelegate(this,this.bodyMouseOver));$("a.h15-group",this._menu).click(Function.createDelegate(this,this.toggleMenu)).mouseover(Function.createDelegate(this,this.triggerShow));if(Sys.Browser.agent==Sys.Browser.InternetExplorer){$("a.h15-link",this._menu).click(Function.createDelegate(this,this.linkClick));}else{$("a.h15-link",this._menu).mousedown(Function.createDelegate(this,this.linkClick));}
$("div.h15-menu-container",this._menu).mouseover(Function.createDelegate(this,this.keepMenuVisible));};Csp.Menu.prototype={bodyKeyPress:function(e){if(e.keyCode==27){var menu=$(".h15-menu-container:visible",this._menu);this.hideMenus();menu.prev("a.h15-group").each(function(){this.focus();});}},bodyMouseOver:function(e){this.clearShower();this.triggerHide();},clearHider:function(){if(this._hider!=null){window.clearTimeout(this._hider);this._hider=null;}},clearShower:function(){if(this._shower!=null){window.clearTimeout(this._shower);this.shower=null;}},doubleQuote:function(s){return s.replace("'","''");},hideMenus:function(e){$("div.h15-groups table td").removeClass("h15-selected");$(".h15-menu-container",this._menu).hide();},keepMenuVisible:function(e){e.stopPropagation();this.clearHider();this.clearShower();},linkClick:function(e){var link=$(e.target);var subgroup=link.parents("ul.h15-links").prev("h6.h15-menu-header");var group=subgroup.parents("div.h15-menu-container").prev("a.h15-group");this.webTrends3(link.text(),subgroup.text(),group.text());},showFlyout:function(e){var count=$(".h15-menu-container",this._menu).length;var index=$(".h15-menu-container",this._menu).index(e);if(document.documentElement.dir!="rtl"){if(index<2){this.showFlyoutLeft(e);}else if(index<count-2){if($(".h15-column:has(.h15-menu)",e).length>1){this.showFlyoutRightMulti(e);}else{this.showFlyoutLeft(e);}}else{if($(".h15-column:has(.h15-menu)",e).length>1){this.showFlyoutLeftMulti(e);}else{this.showFlyoutRight(e);}}}else{if(index<2){this.showFlyoutRight(e);}else if(index<count-2){if($(".h15-column:has(.h15-menu)",e).length>1){this.showFlyoutLeftMulti(e);}else{this.showFlyoutRight(e);}}else{this.showFlyoutLeft(e);}}
e.show();window.setTimeout(function(){$(".h15-m1, .h15-m2, .h15-m3, .h15-m4",e).css("background","#fff");},0);},showFlyoutLeft:function(e){if(document.documentElement.dir=="rtl"){e.css("left",220-e.parent("td").width());}},showFlyoutLeftMulti:function(e){if(document.documentElement.dir=="rtl"){e.css("left",200-e.parent("td").width());}else{e.css("left",-200+e.parent("td").width());}},showFlyoutRight:function(e){if(document.documentElement.dir=="ltr"){e.css("left",-220+e.parent("td").width());}},showFlyoutRightMulti:function(e){e.css("left",-200+e.parent("td").width());},showMenu:function(e){this.hideMenus();var el=$(e.target);el.parent("td").addClass("h15-selected");this.showFlyout(el.next(".h15-menu-container"));if(typeof el.attr("h15:tag")=="undefined"){this.webTrends1(el.text());el.attr("h15:tag","1");}},toggleMenu:function(e){e.preventDefault();this.clearHider();this.clearShower();var el=$(e.target).next(".h15-menu-container");var shown=el.css("display")!="none";this.hideMenus();if(!shown){el.parent("td").addClass("h15-selected");this.showFlyout(el);}},triggerHide:function(){if(this._hider==null){this._hider=window.setTimeout(Function.createDelegate(this,this.hideMenus),1000);}},triggerShow:function(e){e.stopPropagation();this.clearHider();if(this._shower!=null){this.clearShower();}
this._shower=window.setTimeout(Function.createDelegate(this,function(){this.showMenu(e);}),125);},webTrends1:function(name){if(typeof window.dcsMultiTrack!="undefined"){var name=this.doubleQuote(name);try{dcsMultiTrack("DCS.dcsuri",this.normalizePathname(location.pathname),"DCSext.ngn_clevel","Level 1","DCSext.ngn_lname",dcsEscape(dcsEncode(name)),"DCS.ngn_type","Master Navigation","WT.si_p","Level 2a","WT.ti",name+":menu:menu","WT.dl","1","DCS.wt_linkid","");}catch(e){}}},webTrends3:function(name,subgroup,group){if(typeof window.dcsMultiTrack!="undefined"){var campaignID="";var query=(location.search.length>0)?location.search.substring(1):"";var name=this.doubleQuote(name);var title=this.doubleQuote(group)+":"+this.doubleQuote(subgroup)+":"+name;try{dcsMultiTrack("DCS.dcssip",location.hostname,"DCS.dcsuri",this.normalizePathname(location.pathname),"DCS.dcsqry",query,"DCSext.ngn_clevel","Level 2b","DCSext.ngn_lname",dcsEscape(dcsEncode(name)),"DCS.ngn_type","Master Navigation","WT.si_p","Level 3","WT.ti",title,"WT.dl",1,"DCSext.wt_linkid",campaignID);}catch(e){}}},normalizePathname:function(path){return(path.startsWith("/"))?path:"/"+path;}};Csp.Menu.layout=function(layout,menu){var columns=$("div.h15-column",menu);var currentHeight=0;var index=0;var height=0;$("div.h15-menu",layout).each(function(){height=$(this).height()+20;if(currentHeight>0&&index<3&&currentHeight+height>350){index++;currentHeight=0;}
currentHeight+=height;$(this).appendTo(columns[index]);});var menuHeight=0;columns.each(function(){menuHeight=Math.max(menuHeight,$(this).height());});var menuWidth=(index+1)*200;$(menu).height(Math.min(menuHeight,350)+10).width(menuWidth).css({visibility:"visible"});$(".h15-menu-inner",menu).height(menuHeight);columns.each(function(){var column=$(this);var ix=columns.index(this);if(ix<index){column.addClass("h15-dotted");}
if(ix<=index){column.height(menuHeight);}else{column.hide();}});};

if(typeof window.Csp=="undefined"){window.Csp={};}
$$SL=Csp.Silverlight=function(version,interval){var handlers=new $$E();var silverlightVersion=version||"2.0";var timeout=interval||3000;return{displayCreatives:function(){handlers.callHandlers();},get_SilverlightVersion:function(){return silverlightVersion;},refreshCreatives:function(){if(Silverlight.isInstalled(silverlightVersion)){$$SL.displayCreatives();}else if(typeof $$U!="undefined"&&$$U.Browser=="MSIE"){window.setTimeout($$SL.refreshCreatives,timeout);}},registerCreative:function(handler){handlers.addHandler(handler);}};}();var silvergate;$$SG=Csp.SilverGate=function(args){if(args!==null){this._DaysToLive=args.daysToLive||1095;this._InstallID=args.installID;this._IsDirectInstall=args.isDirectInstall||false;this._NoThanksID=args.noThanksID;this._PopupID=args.popupID;this._Version=args.version||"2.0";}
this._CloseHandlers=new $$E();this._InstallHandlers=new $$E();this._ShowHandlers=new $$E();this._UnloadHandlers=new $$E();if(this._InstallID!==null){$addHandler($get(this._InstallID),"click",Function.createDelegate(this,this.onInstallClick));}
if(this._NoThanksID!==null){$addHandler($get(this._NoThanksID),"click",Function.createDelegate(this,this.onCloseClick));}
if($.browser.ie){this._KeyPressHandler=$addHandler(document.body,"keypress",Function.createDelegate(this,this.onKeyPress));}else{this._KeyPressHandler=$addHandler(document,"keypress",Function.createDelegate(this,this.onKeyPress));}
if(typeof $$U!="undefined"){$$U.detectUserAgent();this._InstallUrl="https://web.archive.org/web/20091029104302/http://www.microsoft.com/silverlight/handlers/getsilverlight.ashx?v="+this._Version;}};$$SG.prototype={dispose:function(){if(this._InstallID!==null){$clearHandlers($get(this._InstallID));}
if(this._NoThanksID!==null){$clearHandlers($get(this._NoThanksID));}
if(this._KeyPressHandler!==null){$clearHandlers(document);$clearHandlers(document.body);}},hidePopup:function(){if(this._PageGate!=null){this._PageGate.hide();this._PageGate.dispose();}
this.unloadPopup();},onCloseClick:function(){$$C.setCookie("pgcld","true",this._DaysToLive);if(typeof window.dcsMultiTrack!="undefined"){dcsMultiTrack("DCSext.wt_pg","Page Gate Close","WT.dl","16");}
this.hidePopup();this._CloseHandlers.callHandlers();},onInstallClick:function(){if(typeof window.dcsMultiTrack!="undefined"){dcsMultiTrack("DCSext.wt_pg","Install now","WT.dl","16");}
$$SL.refreshCreatives();location.href=this._InstallUrl;this.hidePopup();this._InstallHandlers.callHandlers();},onKeyPress:function(e){var target=e.target;var keyCode=e.charCode;if(keyCode==13&&target.className.indexOf("sg-ignore-enter")==-1){this.onInstallClick();}else if(keyCode==27){this.onCloseClick();}},registerClose:function(handler){this._CloseHandlers.addHandler(handler);},registerShow:function(handler){this._ShowHandlers.addHandler(handler);},registerUnload:function(handler){this._UnloadHandlers.addHandler(handler);},showPopup:function(){var popup=$get(this._PopupID);if(popup!==null){this._PageGate=new Csp.PageGate(this._PopupID);this._PageGate.show();Sys.UI.DomElement.addCssClass(popup,"sg-popup-image");popup.style.display="block";var installButton=$get(this._InstallID);if(installButton!==null){installButton.focus();}}
if(typeof window.dcsMultiTrack!="undefined"){dcsFunc("dcsCookie");dcsMeta();dcsMultiTrack("DCS.dcssip",window.location.hostname,"DCS.dcsuri",window.location.pathname.substring(0,window.location.pathname.lastIndexOf("/")+1)+"pagegate/","DCSext.wt_sppt",WT.sp+"hp","DCSext.wt_pg","Silverlight Page Gate","WT.dl","15","WT.seg_4","No","DCSext.wt_ver","","DCSext.wt_target","","DCSext.wt_linkid","");}
this._ShowHandlers.callHandlers();},showSilverGate:function(){if($$SG.overridePopup()){$$C.removeCookie("pgcld");this.showPopup();}else if(typeof $$U!="undefined"&&$$U.Browser=="Unsupported"){this.unloadPopup();}else if(typeof $$U!="undefined"&&$$U.Browser=="Safari"&&$$U.OS=="Windows"){this.unloadPopup();}else if(typeof window.Silverlight!="undefined"&&Silverlight.isInstalled(this._Version)){$$SL.displayCreatives();this.unloadPopup();}else if(!$$C.enabled()||$$C.hasCookie("pgcld")){this.unloadPopup();}else{this.showPopup();}},unloadPopup:function(){if(typeof window.dcsRun!="undefined"&&$$SG.get_IsDisplayed()){dcsRun();}
this.dispose();this._UnloadHandlers.callHandlers();$$SG.set_IsUnloaded(true);}};$$SG.get_IsDirectInstall=function(){return this.IsDirectInstall||false;};$$SG.set_IsDirectInstall=function(value){this.IsDirectInstall=value;};$$SG.get_IsDisplayed=function(){return this.IsDisplayed||false;};$$SG.set_IsDisplayed=function(value){this.IsDisplayed=value;};$$SG.get_IsUnloaded=function(){return this.IsUnloaded||false;};$$SG.set_IsUnloaded=function(value){this.IsUnloaded=value;};$$SG.createDirectInstall=function(id,event){$addHandler($get(id),event,function(e){$$U.detectUserAgent();if(typeof window.$$U!="undefined"&&$$U.Browser!="Unsupported"){e.preventDefault();if(typeof window.dcsMultiTrack!="undefined"){var el=$get(this._InstallID);var text=(el!=null)?el.title:"Click to install";dcsMultiTrack("WT.ti","Direct Install: "+text,"DCSext.wt_slditi","Direct Install: "+text,"WT.dl","18");}
$$SL.refreshCreatives();$$SG.set_IsDirectInstall(true);location.href="https://web.archive.org/web/20091029104302/http://www.microsoft.com/silverlight/handlers/getsilverlight.ashx?v="+$$SL.get_SilverlightVersion();}});};$$SG.createPageGate=function(args){this.set_IsDisplayed(this.shouldShowSilverGate(args));if(typeof window.Silverlight!="undefined"&&typeof Silverlight.WaitForInstallCompletion!="undefined"){Silverlight.WaitForInstallCompletion=function(){};}
silvergate=new $$SG({daysToLive:args.daysToLive,installID:args.installID,noThanksID:args.noThanksID,popupID:args.popupID});$().ready(Function.createDelegate(silvergate,silvergate.showSilverGate));};$$SG.overridePopup=function(){return $$Q.hasValue("showPageGate")||$$Q.hasValue("showpagegate");};$$SG.shouldShowSilverGate=function(args){if(this.overridePopup()){return true;}else if(typeof $$U!="undefined"&&$$U.Browser=="Unsupported"){return false;}else if(typeof $$U!="undefined"&&$$U.Browser=="Safari"&&$$U.OS=="Windows"){return false;}else if(typeof window.Silverlight!="undefined"&&Silverlight.isInstalled($$SL.get_SilverlightVersion())){return false;}else if(!args.isDirectInstall&&(!$$C.enabled()||$$C.hasCookie("pgcld"))){return false;}else{return true;}};$$PG=Csp.PageGate=function(popupID){this._popupID=popupID;this.initialize();}
$$PG=Csp.PageGate.prototype={dispose:function(){if(this._ResizeHandler!=null){$removeHandler(window,"resize",this._ResizeHandler);}
if(this._ScrollHandler!=null){$removeHandler(window,"scroll",this._ScrollHandler);}},getClientBounds:function(){var clientWidth;var clientHeight;switch(Sys.Browser.agent){case Sys.Browser.InternetExplorer:clientWidth=document.documentElement.clientWidth;clientHeight=document.documentElement.clientHeight;break;case Sys.Browser.Safari:clientWidth=window.innerWidth;clientHeight=window.innerHeight;break;case Sys.Browser.Opera:clientWidth=Math.min(window.innerWidth,document.body.clientWidth);clientHeight=Math.min(window.innerHeight,document.body.clientHeight);break;default:clientWidth=Math.min(window.innerWidth,document.documentElement.clientWidth);clientHeight=Math.min(window.innerHeight,document.documentElement.clientHeight);break;}
return new Sys.UI.Bounds(0,0,clientWidth,clientHeight);},hide:function(){this._popup.style.display="none";this._backgroundEl.style.display="none";this.turnSelectsOn();this.turnTabsOn();},initialize:function(){if(typeof this._popupID!="undefined"){this._tagsWithTabIndex=["A","AREA","BUTTON","IFRAME","INPUT","OBJECT","SELECT","TEXTAREA"];this._popup=$get(this._popupID);if(typeof this._popup!="undefined"){this._popup.style.position="absolute";this._popup.style.zIndex="10001";if(document.body.childNodes.length>0){document.body.insertBefore(this._popup,document.body.childNodes[0]);}else{document.body.appendChild(this._popup);}
this._ResizeHandler=$addHandler(window,"resize",Function.createDelegate(this,this.onResize));this._ScrollHandler=$addHandler(window,"scroll",Function.createDelegate(this,this.onScroll));this.resize();this.hide();}}},resize:function(){var clientBounds=this.getClientBounds();var clientHeight=clientBounds.height;var clientWidth=clientBounds.width;var scrollTop=document.documentElement.scrollTop?document.documentElement.scrollTop:document.body.scrollTop;var scrollLeft=document.documentElement.scrollLeft?document.documentElement.scrollLeft:document.body.scrollLeft;var scrollHeight=Math.max(document.documentElement.scrollHeight,document.body.scrollHeight);var scrollWidth=Math.max(document.documentElement.scrollWidth,document.body.scrollWidth);if(Sys.Browser.agent===Sys.Browser.InternetExplorer&&Sys.Browser.version==6){var bounds=Sys.UI.DomElement.getBounds(this._popup);if(typeof bounds!="undefined"){this._popup.style.top="20px";this._popup.style.left=(scrollLeft+((clientWidth-bounds.width)/2))+"px";}
var backgroundEl=this._backgroundEl;if(typeof backgroundEl=="undefined"){backgroundEl=this._backgroundEl=document.createElement("DIV");backgroundEl.className="sg-background";backgroundEl.style.left="0px";backgroundEl.style.position="absolute";backgroundEl.style.top="0px";backgroundEl.style.zIndex="10000";if(document.body.childNodes.length>0){document.body.insertBefore(backgroundEl,document.body.childNodes[0]);}else{document.body.appendChild(backgroundEl);}}
backgroundEl.style.height=Math.max(clientHeight,scrollHeight)+"px";backgroundEl.style.width=Math.max(clientWidth,scrollWidth)+"px";}else{var bounds=Sys.UI.DomElement.getBounds(this._popup);if(typeof bounds!="undefined"){this._popup.style.top="20px";this._popup.style.left=((clientWidth-bounds.width)/2)+"px";}
var backgroundEl=this._backgroundEl;if(typeof backgroundEl=="undefined"){backgroundEl=this._backgroundEl=document.createElement("DIV");backgroundEl.className="sg-background";backgroundEl.style.left="0px";backgroundEl.style.position="fixed";backgroundEl.style.top="0px";backgroundEl.style.zIndex="10000";if(document.body.childNodes.length>0){document.body.insertBefore(backgroundEl,document.body.childNodes[0]);}else{document.body.appendChild(backgroundEl);}}
backgroundEl.style.height=Math.max(clientHeight,scrollHeight)+"px";backgroundEl.style.width=Math.max(clientWidth,scrollWidth)+"px";}},show:function(){this._popup.style.display="block";this._backgroundEl.style.display="block";this.resize();this.turnSelectsOff();this.turnTabsOff();},turnSelectsOff:function(){if($.browser.msie&&$.browser.version==6){$("SELECT").css("visibility","hidden");}},turnSelectsOn:function(){if($.browser.msie&&$.browser.version==6){$("SELECT").css("visibility","visible");}},turnTabsOff:function(){var popupEls=[];var els=this._popup.getElementsByTagName("*");for(var i=0;i<els.length;i++){popupEls.push(els[i]);}
this._tabbedEls=[];var allEls=document.getElementsByTagName("*");for(var i=0;i<allEls.length;i++){var el=allEls[i];if(Array.indexOf(popupEls,el)==-1&&Array.indexOf(this._tagsWithTabIndex,el.tagName)!=-1){this._tabbedEls.push({tag:el,index:el.tabIndex});el.tabIndex="-1";}}},turnTabsOn:function(){if(typeof this._tabbedEls!="undefined"){for(var i=0;i<this._tabbedEls.length;i++){var tabbedEl=this._tabbedEls[i];tabbedEl.tag.tabIndex=tabbedEl.index;}}},onResize:function(){this.resize();},onScroll:function(){this.resize();}};


}
/*
     FILE ARCHIVED ON 10:43:02 Oct 29, 2009 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 00:40:15 Apr 06, 2023.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  captures_list: 129.823
  exclusion.robots: 0.121
  exclusion.robots.policy: 0.114
  cdx.remote: 0.043
  esindex: 0.006
  LoadShardBlock: 61.174 (3)
  PetaboxLoader3.datanode: 333.797 (4)
  load_resource: 314.159
  PetaboxLoader3.resolve: 33.081
*/
